/**
 * @author Thaer Aldwaik <t_dwaik@hotmail.com>
 */

app.controller('carsTimelineController', ['$scope', function($scope) {

    $scope.timeline = [
        {"code": "Koenigsegg-One:1", "release_date": 2014, "img": "https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/koenigsegg-one-1-014.jpg?itok=m4qCuo7D", "subTitle": "koenigsegg One:1", "title": "koenigsegg One:1", "description": "The One:1 truly raised the performance bar. The One:1 featured new, unique solutions that enhance track performance without compromising top speed or everyday usability, with a stunning visual appearance to go with it."},
        {"code": "Mercedes-SLS-AMG-Electric", "release_date": 2014, "img": "http://st.automobilemag.com/uploads/sites/11/2013/06/Mercedes-Benz-SLS-AMG-Electric-Drive-on-Ring-5.jpg", "subTitle": "Mercedes-AMG SLS Electric", "title": "Mercedes-AMG SLS Electric", "description": "Not only is the electric supercar AMG’s quietest model by a long way, but it’s also the brand’s most powerful. Electrification provides the SLS with 740 hp and 738 lb-ft of torque, with all the twist available from a standstill. The electricity is generated by four contact permanent-magnet synchronous electric motors that spin to 13,000 rpm and through a so-called axially arranged transmission. In comparison, the new-for-2013 petroleum-powered SLS AMG GT churns out 583 hp and 489 lb-ft. Benz claims the electrified SLS will hit 62 mph in 3.9 seconds before topping out at an electronically limited 155."},
        {"code": "Lexus-LFA", "release_date": 2012, "img": "https://s.aolcdn.com/dims-global/dims3/GLOB/legacy_thumbnail/916x515/quality/95/http://www.blogcdn.com/www.autoblog.com/media/2009/10/lexuslfafd_07.jpg", "subTitle": "Lexus LFA", "title": "Lexus LFA", "description": "The Lexus LFA is a two-seat supercar from Lexus. It is the second model in the F marque line of performance vehicles from Lexus, following the IS F. Three concept versions have been shown, each debuting at the North American International Auto Show with the LF-A designation as part of the LF Series concept line."},
        {"code": "Bugatti-Veyron", "release_date": 2005, "img": "https://upload.wikimedia.org/wikipedia/commons/9/94/Bugatti_Veyron_16.4_%E2%80%93_Frontansicht_%283%29%2C_5._April_2012%2C_D%C3%BCsseldorf.jpg", "subTitle": "Bugatti Veyron", "title": "Bugatti Veyron", "description": "The Bugatti Veyron EB 16.4 is a mid-engined sports car, designed and developed in Germany by the Volkswagen Group and manufactured in Molsheim, France, by Bugatti Automobiles S.A.S., named after the racing driver Pierre Veyron. The original version has a top speed of 407 km/h (253 mph)."},
        {"code": "Nissan-Skyline-GTR-R34", "release_date": 1999, "img": "https://upload.wikimedia.org/wikipedia/commons/7/73/Nissan_Skyline_R34_GT-R_N%C3%BCr_001.jpg", "subTitle": "Nissan Skyline GT-R R34", "title": "Nissan Skyline GT-R R34", "description": "Nismo originally designed the concept of the Z-tune in 2002 when Nissan was putting an end to the R34 Skyline production. The first Z-tune was built in 2003, using a used 2002 Skyline GT-R V·Spec II. It was built with a concept RB26DETT 'Z1' engine"},
        {"code": "Mercedes-AMG", "release_date": 1993, "img": "https://www.mercedes-benz.com/wp-content/uploads/sites/3/2017/07/07-mercedes-benz-vehicles-mercedes-amg-gt-4-c-190-2560x1919-1280x960.jpg", "subTitle": "Mercedes-AMG", "title": "Mercedes-AMG", "description": "Mercedes-AMG GmbH, commonly known as AMG, is the high performance division of Mercedes-Benz. AMG independently hires engineers and manufactures and customizes Mercedes-Benz AMG vehicles."},
        {"code": "Toyota-Supra", "release_date": 1993, "img": "http://dealeraccelerate-all.s3.amazonaws.com/lusso/images/3/9/39/4432_232d0d9c4dcb_low_res.JPG", "subTitle": "Toyota Supra", "title": "Toyota Supra", "description": "The Toyota Supra is a sports car/grand tourer that was produced by Toyota Motor Corporation from 1978 to 2002. "},
        {"code": "Ferrari-F40", "release_date": 1987, "img": "https://upload.wikimedia.org/wikipedia/commons/c/cb/F40_Ferrari_20090509.jpg", "subTitle": "Ferrari F40", "title": "Ferrari F40", "description": "The Ferrari F40 is a mid-engine, rear-wheel drive, two-door coupé sports car built from 1987 to 1992, with the LM and GTE race car versions continuing production until 1994 and 1996 respectively. The successor to the Ferrari 288 GTO, it was designed to celebrate Ferrari's 40th anniversary"},
        {"code": "BMW-E30-M3", "release_date": 1985, "img": "http://orig10.deviantart.net/7f27/f/2009/281/0/9/m_power_by_evertech11.jpg", "subTitle": "BMW E30 M3", "title": "BMW E30 M3", "description": "The BMW M3 is a high-performance version of the BMW 3 Series, developed by BMW's in-house motorsport division"},
        {"code": "Lamborghini-Miura", "release_date": 1966, "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Lamborghini_Miura_Sinsheim.jpg/1200px-Lamborghini_Miura_Sinsheim.jpg", "subTitle": "First Mid-Engine", "title": "Lamborghini Miura", "description": "The Lamborghini Miura is a sports car produced by Italian automaker Lamborghini between 1966 and 1973. The car was possibly the first supercar with a rear mid-engined two-seat layout, although the concept was first pioneered by René Bonnet with the Matra Djet in 1964."},
    ];

    $scope.shareFB = function (car) {

        var ogUrl = 'http://extrabhp.com/car-timeline#' + car.code;
        if($('#og-url').attr('content')) {
            $('#og-url').attr('content', ogUrl);
        }else {
            $('head').append('<meta id="og-url" property="og:url" content="' + ogUrl + '" />');
        }

        if($('#og-title').attr('content')) {
            $('#og-title').attr('content', car.title);
        }else {
            $('head').append('<meta id="og-title" property="og:title" content="' + car.title + '" />');
        }

        if($('#og-description').attr('content')) {
            $('#og-description').attr('content', car.description);
        }else {
            $('head').append('<meta id="og-description" property="og:description" content="' + car.description + '" />');
        }

        if($('#og-image').attr('content')) {
            $('#og-image').attr('content', car.img);
        }else {
            $('head').append('<meta id="og-image" property="og:image" content="' + car.img + '" />');
        }
    }

}]);