/**
 * @author Thaer Aldwaik <t_dwaik@hotmail.com>
 */

app.controller('petrolhead101Controller', ['$scope', '$anchorScroll', function($scope, $anchorScroll) {

    $scope.topics = [
        {code: 'Internal_Combustion_Engine', img: 'https://upload.wikimedia.org/wikipedia/commons/d/dc/4StrokeEngine_Ortho_3D_Small.gif', title: 'Internal Combustion Engine', content: 'An internal combustion engine (ICE) is a heat engine where the combustion of a fuel occurs with an oxidizer (usually air) in a combustion chamber that is an integral part of the working fluid flow circuit. In an internal combustion engine, the expansion of the high-temperature and high-pressure gases produced by combustion applies direct force to some component of the engine. The force is applied typically to pistons, turbine blades, rotor or a nozzle. This force moves the component over a distance, transforming chemical energy into useful mechanical energy.', ref: 'Wikipedia', ref_link: 'https://en.wikipedia.org/wiki/Internal_combustion_engine'},
        {code: 'Differential', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/BAUMA_2004_ZF_Differentialgetriebe.jpg/1920px-BAUMA_2004_ZF_Differentialgetriebe.jpg', title: 'Differential', content: 'Differential used to control the take-up reel of a paper tape reader made by Tally circa 1962. The bevel gears spin freely on their shafts, unless a brake shoe stops the left gear. This causes the planet gear to drive the output shaft at half the speed of the driven gear on the right.', ref: 'Wikipedia', ref_link: 'https://en.wikipedia.org/wiki/Differential_(mechanical_device)'},
        {code: 'Limited-slip_differential', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Limited_slip_diff_cone.jpg/1280px-Limited_slip_diff_cone.jpg', title: 'Limited-slip differential', content: 'A limited-slip differential is a type of differential that allows its two output shafts to rotate at different speeds but limits the maximum difference between the two shafts.', ref: 'Wikipedia', ref_link: 'https://en.wikipedia.org/wiki/Limited-slip_differential'},
        {code: 'Mazda_Wankel_engine', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Wankel-1.jpg/560px-Wankel-1.jpg', title: 'Mazda Wankel engine', content: 'The Mazda Wankel engines comprise a family of car engines produced by Mazda, derived from experiments in the early 1960s by Felix Wankel, a German engineer. Over the years, displacement has been increased and turbocharging has been added.', ref: 'Wikipedia', ref_link: 'https://en.wikipedia.org/wiki/Mazda_Wankel_engine'}
    ]

}]);